name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: npm install

    - name: Run jest tests
      run: CI=true npm test
    
    - name: Run lint
      run: npm run lint

    - name: Run prettify
      run: npm run prettify